train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./load/div2k/DIV2K_train_HR
      repeat: 40
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled-fast
    args:
      inp_size: 48
      scale_max: 4
      augment: true
  batch_size: 16

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./load/div2k/DIV2K_valid_HR
      cache: in_memory
  wrapper:
      name: sr-implicit-downsampled-fast
      args:
        inp_size: 48
        scale_min: 4
        scale_max: 4
  batch_size: 1
eval_type: div2k-4
eval_bsize: 100

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: hiif
  args:
    encoder_spec:
      name: swinir
      args:
        no_upsampling: true
    hidden_dim: 256
    blocks: 16

optimizer:
  name: adam
  args:
    lr: 4.e-4
epoch_max: 1050
cosine_lr_warmup:
  warmup_t: 50
  warmup_lr_init: 2.e-6
  lr_min: 2.e-6

epoch_val: 50
epoch_save: 50

resume: ./save/_train_swinir-hiif/epoch-last.pth