test_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ./load/benchmark/manga109/LRbicx2
      root_path_2: ./load/benchmark/manga109/HR
  wrapper:
    name: sr-implicit-paired-fast
    args: {}
  batch_size: 1
eval_type: benchmark-2
eval_bsize: 300

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

