test_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ./load/benchmark/DIV2K/DIV2K_valid_LRbicx3
      root_path_2: ./load/benchmark/DIV2K/DIV2K_valid_GTmod12
  wrapper:
    name: sr-implicit-paired-fast
    args: {}
  batch_size: 1
eval_type: div2k-3
eval_bsize: 300

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

